# Generated by Django 2.1.2 on 2018-10-18 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181017_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['name'], 'verbose_name': 'Cuestionario', 'verbose_name_plural': 'Cuestionarios'},
        ),
    ]
