# Generated by Django 2.1.2 on 2018-10-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20181017_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Questionary',
        ),
    ]
