# Generated by Django 2.1.2 on 2018-10-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20181018_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='plan2',
            field=models.CharField(max_length=200, verbose_name='Horizonte de Planeación 2'),
        ),
    ]
