# Generated by Django 2.1.2 on 2018-10-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20181018_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
    ]
