# Generated by Django 2.1.2 on 2018-10-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20181021_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionary',
            name='tech_11_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_11_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_11_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_12_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_12_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_12_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_13_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_13_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_13_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_14_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_14_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_14_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_15_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_15_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_15_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_21_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_21_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_21_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_22_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_22_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_22_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_23_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_23_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_23_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_24_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_24_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_24_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_25_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_25_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_25_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_26_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_26_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_26_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_27_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_27_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_27_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_31_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_31_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_31_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_32_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_32_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_32_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_33_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_33_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_33_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_34_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_34_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_34_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_35_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_35_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_35_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_36_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_36_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_36_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_41_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_41_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_41_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_42_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_42_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_42_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_43_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_43_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_43_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_44_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_44_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_44_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_45_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_45_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_45_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_46_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_46_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_46_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_51_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_51_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_51_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_52_act',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_52_p1',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tech_52_p2',
            field=models.CharField(choices=[('0', '----'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=100),
        ),
    ]
