from django.db import models

class Questionary(models.Model):

    QUESTION_CHOISES_C=(
        ('0','----'),
        ('A','A'),
        ('B','B'),
        ('C','C'),
    )
    QUESTION_CHOISES_D=(
        ('0','----'),
        ('A','A'),
        ('B','B'),
        ('C','C'),
        ('D','D'),
    )
    QUESTION_CHOISES_E=(
        ('0','----'),
        ('A','A'),
        ('B','B'),
        ('C','C'),
        ('D','D'),
        ('E','E'),
    )
    QUESTION_CHOISES_F=(
        ('0','----'),
        ('A','A'),
        ('B','B'),
        ('C','C'),
        ('D','D'),
        ('E','E'),
        ('F','F'),
    )

    name = models.CharField(verbose_name="Nombre", max_length=200, unique = True)
    plan1 = models.CharField(verbose_name="Horizonte de Planeación 1", max_length=200)
    plan2 = models.CharField(verbose_name="Horizonte de Planeación 2", max_length=200)
    #SMR
    srm_11_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_11_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_11_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_12_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    srm_12_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    srm_12_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    srm_13_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_C,default='')
    srm_13_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_C,default='')
    srm_13_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_C,default='')

    srm_21_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_21_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_21_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_22_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_22_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_22_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_23_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_23_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_23_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_24_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_24_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_24_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_25_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_25_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_25_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_26_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    srm_26_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    srm_26_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')

    srm_31_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_31_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_31_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_32_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_32_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_32_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_33_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_33_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_33_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_34_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_34_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_34_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    srm_41_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_41_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_41_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_42_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_42_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_42_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_43_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_43_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_43_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    srm_51_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_51_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_51_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_52_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    srm_52_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    srm_52_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    srm_53_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_53_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    srm_53_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    #OS
    os_11_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_C,default='')
    os_11_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_C,default='')
    os_11_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_C,default='')
    os_12_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_C,default='')
    os_12_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_C,default='')
    os_12_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_C,default='')
    os_13_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_13_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_13_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    os_21_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_21_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_21_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_22_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_22_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_22_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_23_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_23_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_23_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_24_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_24_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_24_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_25_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_25_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_25_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    os_31_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    os_31_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    os_31_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    os_32_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    os_32_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    os_32_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    os_33_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    os_33_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    os_33_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    os_34_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_34_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_34_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_35_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    os_35_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    os_35_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    os_36_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_36_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_36_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    os_41_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_41_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_41_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_42_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_42_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_42_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_43_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_43_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_43_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    os_51_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_51_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_51_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_52_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_52_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_52_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_53_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_53_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    os_53_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    #GO
    go_11_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_11_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_11_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_12_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_12_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_12_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_13_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_13_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_13_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_14_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_14_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_14_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_15_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_15_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_15_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    go_21_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_21_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_21_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_22_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_22_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_22_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_23_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_23_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_23_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_24_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_24_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_24_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')

    go_31_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_31_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_31_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_32_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_32_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_32_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_33_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_33_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_33_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_34_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_34_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_34_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_35_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_35_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_35_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_36_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_36_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_36_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')

    go_41_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_41_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_41_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_42_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_42_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_42_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_43_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_43_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_43_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_44_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_44_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_44_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_45_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_45_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_45_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    go_51_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_51_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_51_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    go_52_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_52_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    go_52_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    #WAM
    wam_11_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    wam_11_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    wam_11_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    wam_12_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    wam_12_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    wam_12_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    wam_13_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    wam_13_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    wam_13_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
   
    wam_21_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_21_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_21_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_22_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_22_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_22_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_23_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    wam_23_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    wam_23_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    
    wam_31_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_31_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_31_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_32_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_32_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_32_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_33_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_33_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_33_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_34_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_34_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_34_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_35_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_35_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_35_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_36_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_36_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_36_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_37_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_37_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_37_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')

    wam_41_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_41_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_41_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_42_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_42_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_42_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_43_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_43_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_43_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_44_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_44_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_44_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
  
    wam_51_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_51_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_51_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_52_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_52_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    wam_52_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')

    #TECH
    tech_11_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_11_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_11_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_12_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_12_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_12_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_13_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_13_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_13_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_14_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_14_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_14_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_15_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_15_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_15_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
   
    tech_21_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_21_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_21_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_22_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_22_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_22_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_23_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_23_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_23_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_24_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_24_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_24_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_25_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_25_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_25_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_26_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_26_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_26_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_27_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_27_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_27_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    
    tech_31_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_31_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_31_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_32_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_32_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_32_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_33_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_33_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_33_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_34_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_34_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_34_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_35_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_35_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_35_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_36_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_36_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_36_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
   
    tech_41_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_41_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_41_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_42_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_42_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_42_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_43_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_43_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_43_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_44_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    tech_44_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    tech_44_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    tech_45_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_45_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_45_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_46_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_46_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_46_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
  
    tech_51_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_51_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_51_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    tech_52_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_52_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    tech_52_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')

    #CUST
    cust_11_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_11_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_11_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_12_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_12_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_12_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_13_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_13_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_13_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_14_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_C,default='')
    cust_14_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_C,default='')
    cust_14_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_C,default='')
   
    cust_21_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_21_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_21_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_22_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_22_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_22_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_23_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_23_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_23_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_24_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_24_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_24_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_25_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_25_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_25_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_26_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_26_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_26_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    
    cust_31_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_31_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_31_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_32_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_32_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_32_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_33_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_33_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_33_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_34_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_34_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_34_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_35_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_35_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_35_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_36_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_36_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_36_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_37_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_37_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_37_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_38_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_38_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_38_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_39_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_39_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_39_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
   
    cust_41_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_41_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_41_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_42_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_42_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_42_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_43_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_43_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_43_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_44_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_44_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_44_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_45_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_45_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_45_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_46_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_46_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_46_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_47_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_47_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_47_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
  
    cust_51_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_51_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_51_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_52_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_52_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_52_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_53_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_53_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_53_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    cust_54_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_54_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_54_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_55_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_55_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    cust_55_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    #VCI
    vci_11_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_11_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_11_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_12_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_12_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_12_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_13_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_13_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_13_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_14_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_14_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_14_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_15_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_15_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_15_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
   
    vci_21_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_21_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_21_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_22_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_22_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_22_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_23_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_23_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_23_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_24_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_24_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_24_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    
    vci_31_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_31_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_31_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_32_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_32_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_32_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_33_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_33_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_33_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_34_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_34_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_34_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
   
    vci_41_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_41_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_41_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_42_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_42_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_42_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_43_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    vci_43_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    vci_43_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    vci_44_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    vci_44_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    vci_44_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
     
    vci_51_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_51_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_51_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    vci_52_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    vci_52_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    vci_52_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_F,default='')
    vci_53_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_53_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    vci_53_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    
    #SE
    se_11_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_11_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_11_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_12_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_12_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_12_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_13_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_13_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_13_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_14_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_14_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_14_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
       
    se_21_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_21_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_21_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_22_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_22_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_22_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_23_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_23_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_23_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_24_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_24_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_24_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_25_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_25_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_25_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    
    se_31_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_31_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_31_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_32_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_32_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_32_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_33_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_33_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_33_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_34_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_34_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_34_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
   
    se_41_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_41_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_41_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_42_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_42_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_42_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_43_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_43_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_43_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_44_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_44_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_44_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_45_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_45_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_45_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
     
    se_51_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_51_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_51_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_52_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_52_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_52_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_E,default='')
    se_53_act =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_53_p1 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')
    se_53_p2 =  models.CharField(max_length=100, choices= QUESTION_CHOISES_D,default='')

    #
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de modificación")

    class Meta:
        verbose_name = "Cuestionario"
        verbose_name_plural = "Cuestionarios"
        ordering = ['name',]

    def __str__(self):
        return self.name
